# Generated by Django 2.2 on 2019-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adress',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
